modLoader="javafml"
loaderVersion="[33,)"
license="All rights reserved"
[[mods]]
modId="malum"
version="${file.jarVersion}"
displayName="Malum"
logoFile="malum.png"
credits="The Modding Community"
authors="The Malum Team"
description='''
test
'''
[[dependencies.malum]]
    modId="forge"
    mandatory=true
    versionRange="[34.0.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.malum]]
    modId="curios"
    mandatory=true
    versionRange="[1.16.3-4.0.1.0,)"
    ordering="AFTER"
    side="BOTH"