modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="malum"
version="${file.jarVersion}"
displayName="Malum"
logoFile="malum.png"
credits="The Modding Community"
authors="The Malum Team"
description='''
test
'''
[[dependencies.malum]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.15.1-2.0-beta,)"
    ordering="AFTER"
    side="BOTH"