modLoader="javafml"
loaderVersion="[33,)"
license="All rights reserved"
[[mods]]
modId="malum"
version="${file.jarVersion}"
displayName="Malum"
logoFile="malum.png"
credits="The Minecraft Modding Discord and everyone there.
It's an amazing place full of a ton of amazing people, this mod wouldn't be possible without them.

Jester Hat by Xelo
Tail by TheU1t1mateGuy
"
authors="The Malum Team"
description='''
Malum is a mod about harvesting spirits of innocent creatures.
With these spirits, you can do fun crazy stuff, like:
Breed animals,
Fire a bow,
Erase space and time,
Open your enderchest
And more!
'''
[[dependencies.malum]]
    modId="forge"
    mandatory=true
    versionRange="[34.0.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.malum]]
    modId="curios"
    mandatory=true
    versionRange="[1.16.3-4.0.1.0,)"
    ordering="AFTER"
    side="BOTH"