modLoader="javafml"
loaderVersion="[33,)"
license="All rights reserved"
[[mods]]
modId="malum"
version="${file.jarVersion}"
displayName="Malum"
logoFile="malum.png"
credits='''The Minecraft Modding Discord and everyone there.
It's an amazing place full of a ton of amazing people, this mod wouldn't be possible without them.

Funny Furry Tail by TheU1t1mateGuy
'''
authors="Sammy;"
description='''
Malum is a sinister magic mod;
'''
[[dependencies.malum]]
    modId="forge"
    mandatory=true
    versionRange="[34.0.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.malum]]
    modId="curios"
    mandatory=true
    versionRange="[1.16.3-4.0.1.0,)"
    ordering="AFTER"
    side="BOTH"