
modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="malum"
version="${file.jarVersion}"
displayName="Malum"
authors="Sammy; Lily;"
description='''
A dark magic mod focused on soul and spirit magic.
'''
[[dependencies.malum]]
modId="curios"
mandatory=true
versionRange="[FORGE-1.18.1,)"
ordering="AFTER"
side="BOTH"
[[dependencies.malum]]
modId="tetra"
mandatory=false
versionRange="[FORGE-1.18.1,)"
ordering="AFTER"
side="BOTH"